#!/usr/bin/env bash
#-Metadata----------------------------------------------------#
#  Filename: Sudomy - Subdomain Enumeration & Analysis        #
#-Author(s)---------------------------------------------------#
#  Edo maland ~ @screetsec                                    #
#-Info--------------------------------------------------------#
#  This file is part of Sudomy project                        #
#  Plugin Screenshots: Update = 2022-06-17                    #
#	- gowitness					      #
#-Licence-----------------------------------------------------#
#  MIT License ~ http://opensource.org/licenses/MIT           #
#-------------------------------------------------------------#

function exec_gowitness() {
	rm -rf "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness/*" ## Cleaning old file
	echo -e "\n${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Web Screenshots: from domain list"
	echo -e "---------------------------------------------\n"
	## Check Folder Results
	[[ ! -e "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness" ]] &&
		mkdir -p "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness" || true

	${_GOWITNESS} file -f "${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_HTTPROBE}" \
	--screenshot-path "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness/" \
	--db-path "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness/gowitness.sqlite3" \
	-t 20

	## Reports
	${_GOWITNESS} report export \
	--db-path "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness/gowitness.sqlite3" \
	--file "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness/gowitness_report.html"

	## Start the gowitness report server and open up in new firefox window/tab
	cd "${OUT}/${DATE_LOG}/${DOMAIN}/screenshots/gowitness/"
	${_GOWITNESS} server -A &
	cd - || true
	firefox http://localhost:7171
}
