#!/usr/bin/env bash
#-Metadata----------------------------------------------------#
#  Filename: Sudomy - Subdomain Enumeration & Analysis        #
#-Author(s)---------------------------------------------------#
#  Edo maland ~ @screetsec                                    #
#-Info--------------------------------------------------------#
#  This file is part of Sudomy project                        #
#  Plugin Gobuster : Update = 2020-06-06                      #
#-Licence-----------------------------------------------------#
#  MIT License ~ http://opensource.org/licenses/MIT           #
#-------------------------------------------------------------#

function exec_gobuster() {
       which ${_GOBUSTER} >/dev/null
       if [[ "$?" -eq "0" ]]; then
              echo -e "\n${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Running Bruterforce DNS: Gobuster    "
              echo -e "---------------------------------------------\n"
              ${_GOBUSTER} dns -d ${DOMAIN} --wildcard -qw ${_GOWORDLIST} -o ${OUT_GOBUSTER} | awk '{print $2}' | sed -e 's/^/\t - /'
              cat ${OUT_GOBUSTER} | awk '{print $2}' >${RESULT_GOBUSTER}
              rm -rf ${OUT_GOBUSTER}
       else
              echo -e "${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Running Bruterforce DNS: Gobuster    "
              echo -e "---------------------------------------------\n"
              echo -e "${PADDING}${RESET}${PADDING}${LRED}x${RESET} This Plugin need Gobuster, ${RED}install it${RESET}"

       fi

}
