#!/usr/bin/env bash
#-Metadata----------------------------------------------------#
#  Filename: Sudomy - Subdomain Enumeration & Analysis        #
#-Author(s)---------------------------------------------------#
#  Edo maland ~ @screetsec                                    #
#-Info--------------------------------------------------------#
#  This file is part of Sudomy project                        #
#  Plugin cfcheck: Update = 2020-06-16                        #
#-Licence-----------------------------------------------------#
#  MIT License ~ http://opensource.org/licenses/MIT           #
#-------------------------------------------------------------#

function exec_cfcheck() {
       which ${_CFCHECK} >/dev/null
       if [[ "$?" -eq "0" ]]; then
              echo -e "\n${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Check an IP is Owned by Cloudflare "
              echo -e "---------------------------------------------\n"
              echo -e "\n${PADDING}${YELLOW}${PADDING}⍥${PADDING}${RESET}Execute ${RESET}\n"

              cat ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_IP_RESOLVER} | ${_CFCHECK} -d | tee ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_CFCHECK} | sed -e 's/^/\t - /'
       else
              echo -e "\n${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Check an IP is Owned by Cloudflare  "
              echo -e "---------------------------------------------\n"
              echo -e "${PADDING}${RESET}${PADDING}${LRED}x${RESET} This Plugin need cf-check, ${RED} running the tools again${RESET}"

       fi

}
